GET http://localhost:3000

###

GET http://localhost:3000/dashboard
Content-Type: application/json

{
  "userId": 1
}

###

GET http://localhost:3000/admin

###

GET http://localhost:3000/admin
Content-Type: application/json

{
  "userId": 1
}

###

GET http://localhost:3000/projects
Content-Type: application/json

{
  "userId": 1
}

###

GET http://localhost:3000/projects/1
Content-Type: application/json

{
  "userId": 1
}

###

DELETE http://localhost:3000/projects/1
Content-Type: application/json

{
  "userId": 1
}